spring:
  data:
    mongodb:
      uri: mongodb+srv://disfluency:oFH58ghKTYy0655p@disfluency.4phwfce.mongodb.net/?retryWrites=true&w=majority
      database: disfluency
server:
  port: 8081

amazon:
  aws:
    accessKeyId: AKIA4GKSFFQDZ3UXS3IX
    accessKeySecret: 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
    region: us-east-2